class AddMoreTimeFieldsAgainToResponses < ActiveRecord::Migration
  def change
    add_column :responses, :time118, :integer
    add_column :responses, :time119, :integer
    add_column :responses, :time120, :integer
    add_column :responses, :time121, :integer
    add_column :responses, :time122, :integer
    add_column :responses, :time123, :integer
    add_column :responses, :time124, :integer
    add_column :responses, :time125, :integer
    add_column :responses, :time126, :integer
    add_column :responses, :time127, :integer
    add_column :responses, :time128, :integer
    add_column :responses, :time129, :integer
    add_column :responses, :time130, :integer
    add_column :responses, :time131, :integer
    add_column :responses, :time132, :integer
    add_column :responses, :time133, :integer
    add_column :responses, :time134, :integer
    add_column :responses, :time135, :integer
    add_column :responses, :time136, :integer
    add_column :responses, :time137, :integer
    add_column :responses, :time138, :integer
    add_column :responses, :time139, :integer
    add_column :responses, :time140, :integer
    add_column :responses, :time141, :integer
    add_column :responses, :time142, :integer
    add_column :responses, :time143, :integer
    add_column :responses, :time144, :integer
    add_column :responses, :time145, :integer
    add_column :responses, :time146, :integer
    add_column :responses, :time147, :integer
    add_column :responses, :time148, :integer
    add_column :responses, :time149, :integer
    add_column :responses, :time150, :integer
    add_column :responses, :time151, :integer
    add_column :responses, :time152, :integer
    add_column :responses, :time153, :integer
    add_column :responses, :time154, :integer
    add_column :responses, :time155, :integer
    add_column :responses, :time156, :integer
    add_column :responses, :time157, :integer
    add_column :responses, :time158, :integer
    add_column :responses, :time159, :integer
    add_column :responses, :time160, :integer
    add_column :responses, :time161, :integer
    add_column :responses, :time162, :integer
    add_column :responses, :time163, :integer
    add_column :responses, :time164, :integer
    add_column :responses, :time165, :integer
    add_column :responses, :time166, :integer
    add_column :responses, :time167, :integer
    add_column :responses, :time168, :integer
    add_column :responses, :time169, :integer
    add_column :responses, :time170, :integer
    add_column :responses, :time171, :integer
    add_column :responses, :time172, :integer
    add_column :responses, :time173, :integer
    add_column :responses, :time174, :integer
    add_column :responses, :time175, :integer
    add_column :responses, :time176, :integer
    add_column :responses, :time177, :integer
    add_column :responses, :time178, :integer
    add_column :responses, :time179, :integer
    add_column :responses, :time180, :integer
  end
end
