class AddMoreTimeFieldsToResponses < ActiveRecord::Migration
  def change
    add_column :responses, :time61, :integer
    add_column :responses, :time62, :integer
    add_column :responses, :time63, :integer
    add_column :responses, :time64, :integer
    add_column :responses, :time65, :integer
    add_column :responses, :time66, :integer
    add_column :responses, :time67, :integer
    add_column :responses, :time68, :integer
    add_column :responses, :time69, :integer
    add_column :responses, :time70, :integer
    add_column :responses, :time71, :integer
    add_column :responses, :time72, :integer
    add_column :responses, :time73, :integer
    add_column :responses, :time74, :integer
    add_column :responses, :time75, :integer
    add_column :responses, :time76, :integer
    add_column :responses, :time77, :integer
    add_column :responses, :time78, :integer
    add_column :responses, :time79, :integer
    add_column :responses, :time80, :integer
    add_column :responses, :time81, :integer
    add_column :responses, :time82, :integer
    add_column :responses, :time83, :integer
    add_column :responses, :time84, :integer
    add_column :responses, :time85, :integer
    add_column :responses, :time86, :integer
    add_column :responses, :time87, :integer
    add_column :responses, :time88, :integer
    add_column :responses, :time89, :integer
    add_column :responses, :time90, :integer
    add_column :responses, :time91, :integer
    add_column :responses, :time92, :integer
    add_column :responses, :time93, :integer
    add_column :responses, :time94, :integer
    add_column :responses, :time95, :integer
    add_column :responses, :time96, :integer
    add_column :responses, :time97, :integer
    add_column :responses, :time98, :integer
    add_column :responses, :time99, :integer
    add_column :responses, :time100, :integer
    add_column :responses, :time101, :integer
    add_column :responses, :time102, :integer
    add_column :responses, :time103, :integer
    add_column :responses, :time104, :integer
    add_column :responses, :time105, :integer
    add_column :responses, :time106, :integer
    add_column :responses, :time107, :integer
    add_column :responses, :time108, :integer
    add_column :responses, :time109, :integer
    add_column :responses, :time110, :integer
    add_column :responses, :time111, :integer
    add_column :responses, :time112, :integer
    add_column :responses, :time113, :integer
    add_column :responses, :time114, :integer
    add_column :responses, :time115, :integer
    add_column :responses, :time116, :integer
    add_column :responses, :time117, :integer
  end
end
